# Generated by Django 5.1.7 on 2025-05-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_remove_message_content_remove_message_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
