# Generated by Django 5.2 on 2025-05-18 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='subject',
        ),
        migrations.DeleteModel(
            name='StudentSubject',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
