# Generated by Django 5.2 on 2025-05-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_studentsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='playlist_url',
            field=models.URLField(blank=True),
        ),
    ]
