# Generated by Django 5.2 on 2025-05-21 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_studentvideo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentVideo',
        ),
    ]
