# Generated by Django 5.1.7 on 2025-05-22 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_video_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='heading',
        ),
        migrations.AlterField(
            model_name='video',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.subject'),
            preserve_default=False,
        ),
    ]
