# Generated by Django 5.1.7 on 2025-05-22 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_mcq_usermcqresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermcqresult',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='usermcqresult',
            name='user',
        ),
        migrations.DeleteModel(
            name='MCQ',
        ),
        migrations.DeleteModel(
            name='UserMCQResult',
        ),
    ]
