# Generated by Django 5.2.1 on 2025-05-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_video_completed_video_heading_mcqquestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermcqresponse',
            name='question',
        ),
        migrations.AlterUniqueTogether(
            name='usermcqresponse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usermcqresponse',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='uservideoprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='uservideoprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='uservideoprogress',
            name='video',
        ),
        migrations.RemoveField(
            model_name='video',
            name='completed',
        ),
        migrations.DeleteModel(
            name='MCQQuestion',
        ),
        migrations.DeleteModel(
            name='UserMCQResponse',
        ),
        migrations.DeleteModel(
            name='UserVideoProgress',
        ),
    ]
