# Generated by Django 5.2.1 on 2025-05-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_usermcqresponse_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='heading',
        ),
        migrations.AddField(
            model_name='video',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
