# Generated by Django 5.2.1 on 2025-05-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_video_heading_video_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
