# Generated by Django 5.1.7 on 2025-05-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_payment_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='installment',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='subject',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty')], max_length=10),
        ),
        migrations.DeleteModel(
            name='FeeInstallment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='FeeStructure',
        ),
    ]
