# Generated by Django 5.1.7 on 2025-05-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_test_question_testprogress_testresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testprogress',
            name='question',
        ),
        migrations.RemoveField(
            model_name='test',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='testprogress',
            name='test',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='test',
        ),
        migrations.RemoveField(
            model_name='testprogress',
            name='student',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='student',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestProgress',
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
