# Generated by Django 5.1.7 on 2025-05-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_topic_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('option_a', 'Option A'), ('option_b', 'Option B'), ('option_c', 'Option C'), ('option_d', 'Option D')], max_length=200),
        ),
    ]
