# Generated by Django 5.2.1 on 2025-05-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_question_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
