# Generated by Django 5.2 on 2025-05-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='department',
            field=models.CharField(choices=[('academic', 'Academic Affairs'), ('technical', 'Technical Support'), ('financial', 'Financial Services'), ('student', 'Student Services'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
