# Generated by Django 5.2 on 2025-05-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('low', 'Low')], default='normal', max_length=10),
        ),
    ]
